### ISSUE TITLE
How to use gojs zoom slider in react app

### ISSUE THREAD

**Issue by eswarant** [NorthwoodsSoftware/gojs-react#4] opened 2020-06-09 04:29 UTC
Please do not use the GitHub issue tracker, unless you are reporting a potential bug.

For help and support, please use the GoJS forum: https://forum.nwoods.com/c/gojs

**Comment by jonchardy** [comment] 2020-06-09 12:02
Not a bug and no explanation, closing. If you need help, please post on our forum.

**Closed as completed by jonchardy** 2020-06-09 12:02 UTC
